In [15]:
import pandas as pd

In [16]:
data_clean = pd.read_csv('Data/TamthanWibu.csv')

In [17]:
# Xóa cột có tất cả giá trị là Null
data_clean = data_clean.dropna(axis=1, how='all')

In [18]:
print (data_clean.columns)

Index(['post_id', 'text', 'post_text', 'original_text', 'time', 'timestamp',
       'image', 'image_lowquality', 'images', 'images_description',
       'images_lowquality', 'images_lowquality_description', 'likes',
       'comments', 'shares', 'post_url', 'links', 'user_id', 'username',
       'user_url', 'is_live', 'available', 'comments_full', 'reactors',
       'w3_fb_url', 'reactions', 'reaction_count', 'page_id', 'image_id',
       'image_ids', 'was_live', 'fetched_time'],
      dtype='object')

In [19]:
# lấy biểu cảm của từng bài đăng
def split_reactions(row):
    reaction_dict = eval(row['reactions'])
    return pd.Series(reaction_dict)
reactions = data_clean.apply(split_reactions, axis=1)

In [20]:
reactions

    angry   care    haha     like    love     sad    wow
0     3.0    2.0    17.0   1019.0    35.0  1173.0    4.0
1     5.0    4.0   880.0    746.0    10.0   341.0    8.0
2     1.0    9.0  1166.0   1833.0    27.0    28.0    8.0
3     2.0    5.0  1624.0   1567.0     6.0   312.0    8.0
4     NaN   36.0  2095.0   2825.0   773.0   103.0   47.0
..    ...    ...     ...      ...     ...     ...    ...
95    NaN    8.0  2623.0   5338.0    62.0   325.0   16.0
96    NaN    9.0   397.0    487.0   163.0     5.0    6.0
97    2.0   14.0    27.0   1975.0   264.0  1182.0    5.0
98    1.0   98.0  1476.0   3168.0  2153.0    21.0   49.0
99    6.0  100.0  1947.0  10579.0  2510.0    54.0  105.0

[100 rows x 7 columns]

In [21]:
# Đổi giá trị null sang 0
reactions = reactions.fillna(0)
reactions = reactions.astype('int64')

In [22]:
reactions

    angry  care  haha   like  love   sad  wow
0       3     2    17   1019    35  1173    4
1       5     4   880    746    10   341    8
2       1     9  1166   1833    27    28    8
3       2     5  1624   1567     6   312    8
4       0    36  2095   2825   773   103   47
..    ...   ...   ...    ...   ...   ...  ...
95      0     8  2623   5338    62   325   16
96      0     9   397    487   163     5    6
97      2    14    27   1975   264  1182    5
98      1    98  1476   3168  2153    21   49
99      6   100  1947  10579  2510    54  105

[100 rows x 7 columns]

In [23]:
data_clean

,post_id,text,post_text,original_text,time,timestamp,image,image_lowquality,images,images_description,...,comments_full,reactors,w3_fb_url,reactions,reaction_count,page_id,image_id,image_ids,was_live,fetched_time
0,681246887444577,Lần cuối cùng được nhìn thấy Nobara! 😭💔,Lần cuối cùng được nhìn thấy Nobara! 😭💔,NaN,2023-11-28 18:24:28,1701170668,https://scontent.fhan5-10.fna.fbcdn.net/v/t39....,https://scontent.fhan5-10.fna.fbcdn.net/v/t39....,['https://scontent.fhan5-10.fna.fbcdn.net/v/t3...,"[""May be an image of text that says '3TWIBU 蜗術...",...,"[{'comment_id': '1341150383172011', 'comment_u...",[],https://www.facebook.com/TamthanWibu/posts/681...,"{'like': 1019, 'love': 35, 'haha': 17, 'wow': ...",2253,112017907632948,681249820777617,['681249820777617'],False,2023-11-28 19:30:28.398354
1,681218367447429,Chúc mừng em ❤️,Chúc mừng em ❤️,NaN,2023-11-28 17:11:29,1701166289,https://m.facebook.com/photo/view_full_size/?f...,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,['https://m.facebook.com/photo/view_full_size/...,"[""May be an illustration of text that says 'Em...",...,"[{'comment_id': '1481441082646380', 'comment_u...","[{'name': 'Trần Thuỷ', 'link': 'https://facebo...",https://www.facebook.com/TamthanWibu/posts/681...,"{'like': 746, 'love': 10, 'haha': 880, 'wow': ...",1994,112017907632948,681218064114126,['681218064114126'],False,2023-11-28 19:30:35.804556
2,681191357450130,Màu trắng huyền thoại! 😳\n\nThe legendary whit...,Màu trắng huyền thoại! 😳\n\nThe legendary whit...,Màu trắng huyền thoại! 😳,2023-11-28 15:57:32,1701161852,NaN,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,[],[],...,"[{'comment_id': '1391967235068360', 'comment_u...","[{'name': 'Nguyễn Lê Thiên Kim', 'link': 'http...",https://www.facebook.com/TamthanWibu/posts/681...,"{'like': 1833, 'love': 27, 'haha': 1166, 'wow'...",3072,112017907632948,681191147450151,['681191147450151'],False,2023-11-28 19:31:22.969470
3,681168744119058,Đây mới đúng là một người đàn ông đích thực..\...,Đây mới đúng là một người đàn ông đích thực..\...,Đây mới đúng là một người đàn ông đích thực..,2023-11-28 14:51:25,1701157885,NaN,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,[],[],...,"[{'comment_id': '324917387137328', 'comment_ur...","[{'name': 'Lê Quang Khải', 'link': 'https://fa...",https://www.facebook.com/TamthanWibu/posts/681...,"{'like': 1567, 'love': 6, 'haha': 1624, 'wow':...",3524,112017907632948,681168634119069,['681168634119069'],False,2023-11-28 19:31:30.315713
4,681125257456740,Một Artist đã cosplay lại chính nhân vật mà an...,Một Artist đã cosplay lại chính nhân vật mà an...,NaN,2023-11-28 12:31:43,1701149503,NaN,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,[],[],...,"[{'comment_id': '1449865295562767', 'comment_u...","[{'name': 'Trần Dũng', 'link': 'https://facebo...",https://www.facebook.com/TamthanWibu/posts/681...,"{'like': 2825, 'love': 773, 'haha': 2095, 'wow...",5879,112017907632948,681114634124469,['681114634124469'],False,2023-11-28 19:31:40.409761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,676117784624154,Cảm ơn Sukuna 👍\n\nThank you Sukuna 👍,Cảm ơn Sukuna 👍\n\nThank you Sukuna 👍,Cảm ơn Sukuna 👍,2023-11-18 21:16:56,1700317016,https://scontent.fhan15-1.fna.fbcdn.net/v/t39....,https://scontent.fhan15-1.fna.fbcdn.net/v/t39....,['https://scontent.fhan15-1.fna.fbcdn.net/v/t3...,"[""May be an image of text that says 'Ngươi nhì...",...,"[{'comment_id': '359245726682424', 'comment_ur...","[{'name': 'Bánh Bao Mặn', 'link': 'https://fac...",https://www.facebook.com/TamthanWibu/posts/676...,"{'like': 5338, 'love': 62, 'haha': 2623, 'wow'...",8372,112017907632948,676020087967257,['676020087967257'],False,2023-11-28 19:59:09.063892
96,676094437959822,2 chồng về Việt Nam! 😍😍,2 chồng về Việt Nam! 😍😍,NaN,2023-11-18 20:26:58,1700314018,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,['https://scontent.fhan15-2.fna.fbcdn.net/v/t3...,"[""May be an image of 2 people and text that sa...",...,"[{'comment_id': '897772451937789', 'comment_ur...","[{'name': 'Báo Bình', 'link': 'https://faceboo...",https://www.facebook.com/TamthanWibu/posts/676...,"{'like': 487, 'love': 163, 'haha': 397, 'wow':...",1067,112017907632948,676043944631538,['676043944631538'],False,2023-11-28 19:59:28.108526
97,676061041296495,Nụ cười đã tắt 💔\n\nThe smile was turned off 💔,Nụ cười đã tắt 💔\n\nThe smile was turned off 💔,Nụ cười đã tắt 💔,2023-11-18 19:11:40,1700309500,https://scontent.fhan5-1.fna.fbcdn.net/v/t39.3...,https://scontent.fhan5-1.fna.fbcdn.net/v/t39.3...,['https://scontent.fhan5-1.fna.fbcdn.net/v/t39...,"[""May be an image of text that says '3TWIBU Ng...",...,"[{'comment_id': '270442395983854', 'comment_ur...","[{'name': 'Truc Phuong', 'link': 'https://face...",https://www.facebook.com/TamthanWibu/posts/676...,"{'like': 1975, 'love': 264, 'haha': 27, 'wow':...",3469,112017907632948,676032087966057,['676032087966057'],False,2023-11-28 19:59:50.291319
98,676021787967087,"Tinh hoa hội tụ, phụ nữ gấc iu 🙆🏻‍♀️💗","Tinh hoa hội tụ, phụ nữ gấc iu 🙆🏻‍♀️💗",NaN,2023-11-18 17:33:43,1700303623,https://m.facebook.com/photo/view_full_size/?f...,https://scontent.fsgn5-6.fna.fbcdn.net/v/t39.3...,['https://m.facebook.com/photo/view_full_size/...,['May be an image of 1 person'],...,"[{'comment_id': '340271808591015', 'comment_ur...","[{'name': 'Thienn Lamm', 'link': 'https://face...",https://www.facebook.com/TamthanWibu/posts/676...,"{'like': 3168, 'love': 2153, 'haha': 1476, 'wo...",6966,112017907632948,676020231300576,['676020231300576'],False,2023-11-28 20:00:02.507937
99,675979751304624,Anime và đời thật! 😳\n\nAnime and real life! 😳,Anime và đời thật! 😳\n\nAnime and real life! 😳,Anime và đời thật! 😳,2023-11-18 15:43:36,1700297016,https://scontent.fhan5-1.fna.fbcdn.net/v/t39.3...,https://scontent.fhan5-1.fna.fbcdn.net/v/t39.3...,['https://scontent.fhan5-1.fna.fbcdn.net/v/t39...,['Có thể là hình ảnh về 3 người và văn bản'],...,"[{'comment_id': '2006988256339264', 'comment_u...","[{'name': 'Xuân Điệp', 'link': 'https://facebo...",https://www.facebook.com/TamthanWibu/posts/675...,"{'like': 10579, 'love': 2510, 'haha': 1947, 'w...",15301,112017907632948,675920367977229,['675920367977229'],False,2023-11-28 20:00:16.600017

In [24]:
# liên kết data
data_clean = pd.concat([data_clean, reactions], axis=1)
data_clean.head()

,post_id,text,post_text,original_text,time,timestamp,image,image_lowquality,images,images_description,...,image_ids,was_live,fetched_time,angry,care,haha,like,love,sad,wow
0,681246887444577,Lần cuối cùng được nhìn thấy Nobara! 😭💔,Lần cuối cùng được nhìn thấy Nobara! 😭💔,NaN,2023-11-28 18:24:28,1701170668,https://scontent.fhan5-10.fna.fbcdn.net/v/t39....,https://scontent.fhan5-10.fna.fbcdn.net/v/t39....,['https://scontent.fhan5-10.fna.fbcdn.net/v/t3...,"[""May be an image of text that says '3TWIBU 蜗術...",...,['681249820777617'],False,2023-11-28 19:30:28.398354,3,2,17,1019,35,1173,4
1,681218367447429,Chúc mừng em ❤️,Chúc mừng em ❤️,NaN,2023-11-28 17:11:29,1701166289,https://m.facebook.com/photo/view_full_size/?f...,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,['https://m.facebook.com/photo/view_full_size/...,"[""May be an illustration of text that says 'Em...",...,['681218064114126'],False,2023-11-28 19:30:35.804556,5,4,880,746,10,341,8
2,681191357450130,Màu trắng huyền thoại! 😳\n\nThe legendary whit...,Màu trắng huyền thoại! 😳\n\nThe legendary whit...,Màu trắng huyền thoại! 😳,2023-11-28 15:57:32,1701161852,NaN,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,[],[],...,['681191147450151'],False,2023-11-28 19:31:22.969470,1,9,1166,1833,27,28,8
3,681168744119058,Đây mới đúng là một người đàn ông đích thực..\...,Đây mới đúng là một người đàn ông đích thực..\...,Đây mới đúng là một người đàn ông đích thực..,2023-11-28 14:51:25,1701157885,NaN,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,[],[],...,['681168634119069'],False,2023-11-28 19:31:30.315713,2,5,1624,1567,6,312,8
4,681125257456740,Một Artist đã cosplay lại chính nhân vật mà an...,Một Artist đã cosplay lại chính nhân vật mà an...,NaN,2023-11-28 12:31:43,1701149503,NaN,https://scontent.fhan15-2.fna.fbcdn.net/v/t39....,[],[],...,['681114634124469'],False,2023-11-28 19:31:40.409761,0,36,2095,2825,773,103,47

In [25]:
# đổi kiểu dữ liệu fetched_time thành datetime64
data_clean['time'] = pd.to_datetime(data_clean['time'])
data_clean['time']

0    2023-11-28 18:24:28
1    2023-11-28 17:11:29
2    2023-11-28 15:57:32
3    2023-11-28 14:51:25
4    2023-11-28 12:31:43
             ...
95   2023-11-18 21:16:56
96   2023-11-18 20:26:58
97   2023-11-18 19:11:40
98   2023-11-18 17:33:43
99   2023-11-18 15:43:36
Name: time, Length: 100, dtype: datetime64[ns]

In [26]:
# lấy thời gian đăng của mỗi bài
data_clean['hour'] = data_clean['time'].dt.hour
data_clean['day'] = data_clean['time'].dt.day
data_clean['month'] = data_clean['time'].dt.month
data_clean['year'] = data_clean['time'].dt.year
data_clean[['hour', 'day', 'month', 'year']]

    hour  day  month  year
0     18   28     11  2023
1     17   28     11  2023
2     15   28     11  2023
3     14   28     11  2023
4     12   28     11  2023
..   ...  ...    ...   ...
95    21   18     11  2023
96    20   18     11  2023
97    19   18     11  2023
98    17   18     11  2023
99    15   18     11  2023

[100 rows x 4 columns]

In [27]:
data_clean.to_csv('Data/data_clean.csv', index=False)